name: Advanced Metrics

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  base:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate github-metrics.svg
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Geobatpo07
          committer_branch: main
          filename: github-metrics.svg
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_habits: yes
          plugin_habits_charts_type: bar
          plugin_calendar: yes
          plugin_calendar_limit: 12
